package daoexample.dao;

import daoexample.domain.Customer;
import org.junit.jupiter.api.*;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;


class CustomerDaoTest {

    // === Fields ===

    private static CustomerDao customerDao;

    // === Setup ===

    @BeforeAll
    static void setUp() throws Exception {
        customerDao = new JdbcCustomerDao();
    }

    @BeforeEach
    void cleanUpTestData() throws Exception {
        for (Customer c : customerDao.getAllCustomers()) {
            if (c.getEmail() != null && c.getEmail().startsWith("test.")) {
                customerDao.deleteCustomerById(c.getCustomerId());
            }
        }
    }


    // TEST 1: Get by ID - returns customer when ID exists
    @Test
    void getCustomerById_returnsCustomer_whenIdExists() throws Exception {
        Customer testCustomer = new Customer(
                "John", "ReadTest", "1234567890",
                "test.read@example.com", "123 Test Street"
        );
        Customer saved = customerDao.insert(testCustomer);

        Optional<Customer> found = customerDao.getCustomerById(saved.getCustomerId());

        assertTrue(found.isPresent(), "Customer should be found");
        assertEquals("John", found.get().getFirstName());
    }

    // TEST 2: Get by ID - returns empty when ID does not exist
    @Test
    void getCustomerById_returnsEmptyOptional_whenIdDoesNotExist() throws Exception {
        Optional<Customer> found = customerDao.getCustomerById(999999);
        assertTrue(found.isEmpty(), "Should return empty for fake ID");
    }

    // TEST 3: Insert returns customer with auto-generated ID
    @Test
    void insert_returnsCustomerWithAutoGeneratedId() throws Exception {
        Customer newCustomer = new Customer(
                "Auto", "IdTest", "9876543210",
                "test.autoid@example.com", "456 Auto Avenue"
        );

        Customer saved = customerDao.insert(newCustomer);

        assertTrue(saved.getCustomerId() > 0, "ID should be auto-generated");
        assertEquals("Auto", saved.getFirstName());
    }

    // TEST 4: JSON round-trip
    @Test
    void customerJson_roundTrip_producesSameData() throws Exception {
        Customer original = new Customer(
                42, "Json", "RoundTrip", "5555555555",
                "test.json@example.com", "789 JSON Boulevard"
        );

        String json = customerDao.customerToJson(original);
        Customer restored = customerDao.customerFromJson(json);

        assertEquals(original.getCustomerId(), restored.getCustomerId());
        assertEquals(original.getFirstName(), restored.getFirstName());
        assertEquals(original.getLastName(), restored.getLastName());
    }

    // =========================================================
    // Stage 4 additions (F23)
    // =========================================================

    // TEST 5: getAll returns a non-null list
    @Test
    void getAllCustomers_returnsNonNullList() throws Exception {
        List<Customer> all = customerDao.getAllCustomers();
        assertNotNull(all, "getAllCustomers() should never return null");
    }

    // TEST 6: update changes the customer fields and returns updated entity
    @Test
    void updateCustomer_returnsUpdatedCustomer_whenIdExists() throws Exception {
        Customer inserted = customerDao.insert(new Customer(
                "UpdateMe", "OriginalLast", "0800000001",
                "test.update.original@example.com", "1 Old Road"));

        Customer updatedData = new Customer(
                "UpdateMe", "NewLastName", "0800000099",
                "test.update.new@example.com", "99 New Road");

        Customer result = customerDao.updateCustomer(inserted.getCustomerId(), updatedData);

        assertEquals("NewLastName", result.getLastName(),
                "Last name should be updated");
        assertEquals("0800000099", result.getPhoneNumber(),
                "Phone number should be updated");
    }

    // TEST 7: delete removes the customer from the database
    @Test
    void deleteCustomerById_returnsTrue_whenCustomerExists() throws Exception {
        Customer inserted = customerDao.insert(new Customer(
                "DeleteMe", "Test", "0800000002",
                "test.delete@example.com", "2 Delete Street"));

        boolean deleted = customerDao.deleteCustomerById(inserted.getCustomerId());

        assertTrue(deleted, "Delete should return true for an existing customer");
        Optional<Customer> after = customerDao.getCustomerById(inserted.getCustomerId());
        assertTrue(after.isEmpty(), "Customer should not be found after deletion");
    }

    // TEST 8: delete returns false for a non-existent ID
    @Test
    void deleteCustomerById_returnsFalse_whenIdDoesNotExist() throws Exception {
        boolean deleted = customerDao.deleteCustomerById(999999);
        assertFalse(deleted, "Delete should return false for non-existent ID");
    }

    // TEST 9: filter returns only matching customers
    @Test
    void findCustomersByFilter_returnsMatchingCustomers_whenPredicateApplied() throws Exception {
        customerDao.insert(new Customer(
                "FilterTarget", "Unique", "0800000003",
                "test.filter@example.com", "3 Filter Lane"));

        List<Customer> filtered = customerDao.findCustomersByFilter(
                c -> c.getFirstName().equals("FilterTarget"));

        assertFalse(filtered.isEmpty(), "Should return at least one matching customer");
        filtered.forEach(c -> assertEquals("FilterTarget", c.getFirstName()));
    }

    // TEST 10: JSON list round-trip preserves count and first name
    @Test
    void customerListJson_roundTrip_preservesContent() throws Exception {
        Customer c1 = new Customer(10, "Alice", "Smith", "0811111111",
                "test.alice@example.com", "1 Alice Ave");
        Customer c2 = new Customer(11, "Bob", "Jones", "0822222222",
                "test.bob@example.com", "2 Bob Road");

        List<Customer> list = List.of(c1, c2);
        String json = customerDao.customerListToJson(list);

        assertNotNull(json, "List JSON should not be null");
        assertTrue(json.startsWith("[") && json.endsWith("]"),
                "List JSON should be a JSON array");
        assertTrue(json.contains("Alice"), "List JSON should contain first customer's name");
        assertTrue(json.contains("Bob"), "List JSON should contain second customer's name");
    }

    // TEST 11: getById returns empty Optional for id <= 0 (boundary check)
    @Test
    void getCustomerById_returnsEmpty_whenIdIsZeroOrNegative() throws Exception {
        Optional<Customer> zeroResult = customerDao.getCustomerById(0);
        Optional<Customer> negResult  = customerDao.getCustomerById(-3);

        assertTrue(zeroResult.isEmpty(), "ID 0 should return empty Optional");
        assertTrue(negResult.isEmpty(),  "Negative ID should return empty Optional");
    }
}