package daoexample.dao;

import daoexample.domain.Customer;
import org.junit.jupiter.api.*;
import java.util.List;
import java.util.Optional;
import static org.junit.jupiter.api.Assertions.*;

class CustomerDaoTest {

    private static CustomerDao customerDao;

    @BeforeAll
    static void setUp() throws Exception {
        customerDao = new JdbcCustomerDao();
    }

    @BeforeEach
    void cleanUpTestData() throws Exception {
        for (Customer c : customerDao.getAllCustomers()) {
            if (c.getEmail() != null && c.getEmail().startsWith("test.")) {
                customerDao.deleteCustomerById(c.getCustomerId());
            }
        }
    }

    // TEST 1: Get by ID - returns customer when ID exists
    @Test
    void getCustomerById_returnsCustomer_whenIdExists() throws Exception {
        Customer testCustomer = new Customer(
                "John", "ReadTest", "1234567890",
                "test.read@example.com", "123 Test Street"
        );
        Customer saved = customerDao.insert(testCustomer);

        Optional<Customer> found = customerDao.getCustomerById(saved.getCustomerId());

        assertTrue(found.isPresent(), "Customer should be found");
        assertEquals("John", found.get().getFirstName());
    }

    // TEST 2: Get by ID - returns empty when ID does not exist
    @Test
    void getCustomerById_returnsEmptyOptional_whenIdDoesNotExist() throws Exception {
        Optional<Customer> found = customerDao.getCustomerById(999999);
        assertTrue(found.isEmpty(), "Should return empty for fake ID");
    }

    // TEST 3: Insert returns customer with auto-generated ID
    @Test
    void insert_returnsCustomerWithAutoGeneratedId() throws Exception {
        Customer newCustomer = new Customer(
                "Auto", "IdTest", "9876543210",
                "test.autoid@example.com", "456 Auto Avenue"
        );

        Customer saved = customerDao.insert(newCustomer);

        assertTrue(saved.getCustomerId() > 0, "ID should be auto-generated");
        assertEquals("Auto", saved.getFirstName());
    }

    // TEST 4: JSON round-trip
    @Test
    void customerJson_roundTrip_producesSameData() throws Exception {
        Customer original = new Customer(
                42, "Json", "RoundTrip", "5555555555",
                "test.json@example.com", "789 JSON Boulevard"
        );

        String json = customerDao.customerToJson(original);
        Customer restored = customerDao.customerFromJson(json);

        assertEquals(original.getCustomerId(), restored.getCustomerId());
        assertEquals(original.getFirstName(), restored.getFirstName());
        assertEquals(original.getLastName(), restored.getLastName());
    }
}