package daoexample.dao;

import daoexample.domain.ServiceJob;
import org.junit.jupiter.api.*;

import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;


class ServiceJobDaoTest {

    // === Fields ===

    private static ServiceJobDao serviceJobDao;


    private static final int SEED_VEHICLE_ID = 1;

    // === Setup ===

    @BeforeAll
    static void setUp() throws Exception {
        serviceJobDao = new JdbcServiceJobDao();
    }

    @BeforeEach
    void cleanUpTestData() throws Exception {
        // Removes any service jobs inserted by tests (identified by description prefix "TEST-")
        for (ServiceJob j : serviceJobDao.getAllServiceJobs()) {
            if (j.getDescription() != null && j.getDescription().startsWith("TEST-")) {
                serviceJobDao.deleteServiceJobById(j.getServiceJobId());
            }
        }
    }

    // === Tests ===

    // TEST 1: getAll returns a non-null list
    @Test
    void getAllServiceJobs_returnsNonNullList() throws Exception {
        List<ServiceJob> all = serviceJobDao.getAllServiceJobs();
        assertNotNull(all, "getAllServiceJobs() should never return null");
    }

    // TEST 2: getById returns empty Optional for non-existent ID
    @Test
    void getServiceJobById_returnsEmpty_whenIdDoesNotExist() throws Exception {
        Optional<ServiceJob> result = serviceJobDao.getServiceJobById(999999);
        assertTrue(result.isEmpty(), "Should return empty Optional for non-existent ID");
    }

    // TEST 3: getById returns correct job after insert
    @Test
    void getServiceJobById_returnsJob_whenIdExists() throws Exception {
        ServiceJob inserted = serviceJobDao.insert(new ServiceJob(
                SEED_VEHICLE_ID, "TEST-OilChange", "PENDING", 55.00, "2026-01-10"));

        Optional<ServiceJob> found = serviceJobDao.getServiceJobById(inserted.getServiceJobId());

        assertTrue(found.isPresent(), "Service job should be found after insert");
        assertEquals("TEST-OilChange", found.get().getDescription());
    }

    // TEST 4: insert returns job with a positive auto-generated ID
    @Test
    void insert_returnsServiceJobWithAutoGeneratedId() throws Exception {
        ServiceJob saved = serviceJobDao.insert(new ServiceJob(
                SEED_VEHICLE_ID, "TEST-BrakeCheck", "PENDING", 40.00, "2026-02-01"));

        assertTrue(saved.getServiceJobId() > 0,
                "Inserted service job should have a positive auto-generated ID");
    }

    // TEST 5: update changes fields and returns updated entity
    @Test
    void updateServiceJob_returnsUpdatedJob_whenIdExists() throws Exception {
        ServiceJob original = serviceJobDao.insert(new ServiceJob(
                SEED_VEHICLE_ID, "TEST-TyreRotation", "PENDING", 30.00, "2026-03-01"));

        ServiceJob updated = serviceJobDao.updateServiceJob(original.getServiceJobId(),
                new ServiceJob(SEED_VEHICLE_ID, "TEST-TyreRotation", "COMPLETED", 35.00, "2026-03-05"));

        assertEquals("COMPLETED", updated.getStatus());
        assertEquals(35.00, updated.getCost(), 0.001);
    }

    // TEST 6: delete removes the job from the database
    @Test
    void deleteServiceJobById_returnsTrue_whenJobExists() throws Exception {
        ServiceJob inserted = serviceJobDao.insert(new ServiceJob(
                SEED_VEHICLE_ID, "TEST-Exhaust", "PENDING", 120.00, "2026-04-01"));

        boolean deleted = serviceJobDao.deleteServiceJobById(inserted.getServiceJobId());

        assertTrue(deleted, "Delete should return true for an existing service job");
        Optional<ServiceJob> after = serviceJobDao.getServiceJobById(inserted.getServiceJobId());
        assertTrue(after.isEmpty(), "Service job should not exist after deletion");
    }

    // TEST 7: delete returns false for a non-existent ID
    @Test
    void deleteServiceJobById_returnsFalse_whenIdDoesNotExist() throws Exception {
        boolean deleted = serviceJobDao.deleteServiceJobById(999999);
        assertFalse(deleted, "Delete should return false for non-existent ID");
    }

    // TEST 8: filter returns only jobs matching the predicate
    @Test
    void findServiceJobsByFilter_returnsMatchingJobs_whenPredicateApplied() throws Exception {
        serviceJobDao.insert(new ServiceJob(
                SEED_VEHICLE_ID, "TEST-GlassRepair", "COMPLETED", 200.00, "2026-05-01"));

        List<ServiceJob> filtered = serviceJobDao.findServiceJobsByFilter(
                j -> "COMPLETED".equals(j.getStatus()));

        assertFalse(filtered.isEmpty(), "Filter should return at least one COMPLETED job");
        filtered.forEach(j -> assertEquals("COMPLETED", j.getStatus()));
    }

    // TEST 9: JSON round-trip produces the same data (F9 / F23)
    @Test
    void serviceJobJson_roundTrip_producesSameData() throws Exception {
        ServiceJob original = new ServiceJob(
                5, 1, "TEST-JsonJob", "PENDING", 99.99, "2026-06-01");

        String json = serviceJobDao.serviceJobToJson(original);
        ServiceJob restored = serviceJobDao.serviceJobFromJson(json);

        assertEquals(original.getServiceJobId(), restored.getServiceJobId());
        assertEquals(original.getVehicleId(), restored.getVehicleId());
        assertEquals(original.getCost(), restored.getCost(), 0.001);
        assertEquals(original.getStatus(), restored.getStatus());
    }

    // TEST 10: Binary file upload — stored bytes match retrieved bytes (F18/F19 / F23)
    @Test
    void binaryFileUpload_andRetrieval_bytesMatchOriginal() throws Exception {
        // Arrange: create a service job first
        ServiceJob job = serviceJobDao.insert(new ServiceJob(
                SEED_VEHICLE_ID, "TEST-FileUpload", "PENDING", 0.00, "2026-07-01"));

        // Simulate a small binary file (e.g., a tiny PNG-like byte array)
        byte[] originalBytes = new byte[]{
                (byte) 0x89, 0x50, 0x4E, 0x47,   // PNG magic bytes
                0x0D, 0x0A, 0x1A, 0x0A,            // more PNG header
                0x00, 0x01, 0x02, 0x03             // dummy payload
        };

        // Act: update the job with the file data (simulates what the server does after Base64 decode)
        ServiceJob withFile = new ServiceJob(
                job.getServiceJobId(),
                job.getVehicleId(),
                job.getDescription(),
                job.getStatus(),
                job.getCost(),
                job.getDateCreated(),
                originalBytes,
                "test-receipt.png",
                "image/png",
                originalBytes.length
        );
        serviceJobDao.updateServiceJob(job.getServiceJobId(), withFile);

        // Assert: retrieve the job and compare bytes
        Optional<ServiceJob> retrieved = serviceJobDao.getServiceJobById(job.getServiceJobId());

        assertTrue(retrieved.isPresent(), "Job should be retrievable after file upload");
        assertNotNull(retrieved.get().getFileData(), "File data should not be null after upload");
        assertArrayEquals(originalBytes, retrieved.get().getFileData(),
                "Retrieved bytes should exactly match the uploaded bytes");
        assertEquals("test-receipt.png", retrieved.get().getFileName());
        assertEquals("image/png", retrieved.get().getContentType());
        assertEquals(originalBytes.length, retrieved.get().getFileSize());
    }

    // TEST 11: Metadata query does NOT return file data (F20 / F23)
    @Test
    void getServiceJobMetadataById_returnsMetadataOnly_withoutFileData() throws Exception {
        // Arrange: insert job with file data
        byte[] fileBytes = "Hello, metadata test!".getBytes();
        ServiceJob job = serviceJobDao.insert(new ServiceJob(
                SEED_VEHICLE_ID, "TEST-Metadata", "PENDING", 0.00, "2026-08-01",
                fileBytes, "doc.txt", "text/plain", fileBytes.length));

        // Act: get metadata only
        ServiceJob metadata = serviceJobDao.getServiceJobMetadataById(job.getServiceJobId());

        // Assert: metadata fields present, BLOB absent
        assertNotNull(metadata, "Metadata result should not be null");
        assertEquals("doc.txt", metadata.getFileName());
        assertEquals("text/plain", metadata.getContentType());
        assertTrue(metadata.getFileSize() > 0, "File size should be positive");
        assertNull(metadata.getFileData(),
                "Metadata query should NOT return the binary file data");
    }

    // TEST 12: getById with id <= 0 returns empty Optional (boundary check)
    @Test
    void getServiceJobById_returnsEmpty_whenIdIsZeroOrNegative() throws Exception {
        Optional<ServiceJob> zeroResult = serviceJobDao.getServiceJobById(0);
        Optional<ServiceJob> negResult  = serviceJobDao.getServiceJobById(-1);

        assertTrue(zeroResult.isEmpty(), "ID 0 should return empty Optional");
        assertTrue(negResult.isEmpty(),  "Negative ID should return empty Optional");
    }
}