package daoexample.dao;

import daoexample.domain.Vehicle;
import org.junit.jupiter.api.*;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

/**
 * F23: Extended test suite — covers all VehicleDao methods.
 *
 * @author [Your Name] (primary)
 */
class VehicleDaoTest {

    private static VehicleDao vehicleDao;

    // === Fields ===

    /** A customer ID that must exist in the database (seed data). */
    private static final int SEED_CUSTOMER_ID = 1;

    // === Setup ===

    @BeforeAll
    static void setUp() throws Exception {
        vehicleDao = new JdbcVehicleDao();
    }

    @BeforeEach
    void cleanUpTestData() throws Exception {
        // Removes any vehicles inserted by tests (identified by reg prefix "TEST-")
        for (Vehicle v : vehicleDao.getAllVehicles()) {
            if (v.getRegistrationNumber() != null
                    && v.getRegistrationNumber().startsWith("TEST")) {
                vehicleDao.deleteVehicleById(v.getVehicleId());
            }
        }
    }

    // === Tests ===

    // TEST 1: getAll returns a non-null list (may be empty if no seed data)
    @Test
    void getAllVehicles_returnsNonNullList() throws Exception {
        List<Vehicle> all = vehicleDao.getAllVehicles();
        assertNotNull(all, "getAllVehicles() should never return null");
    }

    // TEST 2: getById returns empty Optional for a non-existent ID
    @Test
    void getVehicleById_returnsEmpty_whenIdDoesNotExist() throws Exception {
        Optional<Vehicle> result = vehicleDao.getVehicleById(999999);
        assertTrue(result.isEmpty(), "Should return empty Optional for non-existent ID");
    }

    // TEST 3: getById returns the correct vehicle after insert
    @Test
    void getVehicleById_returnsVehicle_whenIdExists() throws Exception {
        Vehicle inserted = vehicleDao.insert(new Vehicle(
                SEED_CUSTOMER_ID, "Toyota", "Corolla", "TEST-001-ZZ", 2020));

        Optional<Vehicle> found = vehicleDao.getVehicleById(inserted.getVehicleId());

        assertTrue(found.isPresent(), "Vehicle should be found after insert");
        assertEquals("Toyota", found.get().getMake());
        assertEquals("COROLLA", found.get().getModel().toUpperCase());
    }

    // TEST 4: insert returns vehicle with a positive auto-generated ID
    @Test
    void insert_returnsVehicleWithAutoGeneratedId() throws Exception {
        Vehicle saved = vehicleDao.insert(new Vehicle(
                SEED_CUSTOMER_ID, "Ford", "Focus", "TEST-002-ZZ", 2019));

        assertTrue(saved.getVehicleId() > 0,
                "Inserted vehicle should have a positive auto-generated ID");
        assertEquals("Ford", saved.getMake());
    }

    // TEST 5: update changes the vehicle fields and returns the updated entity
    @Test
    void updateVehicle_returnsUpdatedVehicle_whenIdExists() throws Exception {
        Vehicle original = vehicleDao.insert(new Vehicle(
                SEED_CUSTOMER_ID, "Nissan", "Micra", "TEST-003-ZZ", 2018));

        Vehicle updated = vehicleDao.updateVehicle(original.getVehicleId(),
                new Vehicle(SEED_CUSTOMER_ID, "Nissan", "Juke", "TEST-003-ZZ", 2022));

        assertEquals("Juke", updated.getModel());
        assertEquals(2022, updated.getYear());
    }

    // TEST 6: delete removes the vehicle from the database
    @Test
    void deleteVehicleById_returnsTrue_whenVehicleExists() throws Exception {
        Vehicle inserted = vehicleDao.insert(new Vehicle(
                SEED_CUSTOMER_ID, "Kia", "Ceed", "TEST-004-ZZ", 2021));

        boolean deleted = vehicleDao.deleteVehicleById(inserted.getVehicleId());

        assertTrue(deleted, "Delete should return true for an existing vehicle");
        Optional<Vehicle> after = vehicleDao.getVehicleById(inserted.getVehicleId());
        assertTrue(after.isEmpty(), "Vehicle should not exist after deletion");
    }

    // TEST 7: delete returns false for a non-existent ID
    @Test
    void deleteVehicleById_returnsFalse_whenIdDoesNotExist() throws Exception {
        boolean deleted = vehicleDao.deleteVehicleById(999999);
        assertFalse(deleted, "Delete should return false for non-existent ID");
    }

    // TEST 8: filter returns only vehicles matching the predicate
    @Test
    void findVehiclesByFilter_returnsMatchingVehicles_whenPredicateApplied() throws Exception {
        vehicleDao.insert(new Vehicle(
                SEED_CUSTOMER_ID, "BMW", "M3", "TEST-005-ZZ", 2023));

        List<Vehicle> filtered = vehicleDao.findVehiclesByFilter(
                v -> v.getMake().equalsIgnoreCase("BMW"));

        assertFalse(filtered.isEmpty(), "Filter should return at least one BMW");
        filtered.forEach(v -> assertEquals("BMW", v.getMake()));
    }

    // TEST 9: JSON round-trip produces the same data
    @Test
    void vehicleJson_roundTrip_producesSameData() throws Exception {
        Vehicle original = new Vehicle(7, 1, "Honda", "Civic", "TEST-006-ZZ", 2021);

        String json = vehicleDao.vehicleToJson(original);
        Vehicle restored = vehicleDao.vehicleFromJson(json);

        assertEquals(original.getVehicleId(), restored.getVehicleId());
        assertEquals(original.getMake(), restored.getMake());
        assertEquals(original.getModel(), restored.getModel());
        assertEquals(original.getYear(), restored.getYear());
    }

    // TEST 10: JSON list round-trip preserves count and content
    @Test
    void vehicleListJson_roundTrip_preservesCountAndContent() throws Exception {
        Vehicle v1 = vehicleDao.insert(new Vehicle(
                SEED_CUSTOMER_ID, "Peugeot", "208", "TEST-007-ZZ", 2020));
        Vehicle v2 = vehicleDao.insert(new Vehicle(
                SEED_CUSTOMER_ID, "Renault", "Clio", "TEST-008-ZZ", 2021));

        List<Vehicle> list = List.of(v1, v2);
        String json = vehicleDao.vehicleListToJson(list);

        assertNotNull(json);
        assertTrue(json.startsWith("[") && json.endsWith("]"),
                "List JSON should be a JSON array");
        assertTrue(json.contains("Peugeot"), "List JSON should contain first vehicle's make");
        assertTrue(json.contains("Renault"), "List JSON should contain second vehicle's make");
    }

    // TEST 11: getById with id <= 0 returns empty Optional (boundary check)
    @Test
    void getVehicleById_returnsEmpty_whenIdIsZeroOrNegative() throws Exception {
        Optional<Vehicle> zeroResult = vehicleDao.getVehicleById(0);
        Optional<Vehicle> negResult  = vehicleDao.getVehicleById(-5);

        assertTrue(zeroResult.isEmpty(), "ID 0 should return empty Optional");
        assertTrue(negResult.isEmpty(),  "Negative ID should return empty Optional");
    }
}